Feature/your order
SergeyMyronenko/ukrainian-style pull request #10
Opened 2023-10-02 10:33 UTC by AnnaMakovska

Creates tour order section

2023-10-02 12:57 UTC, SergeyMyronenko requested changes

2023-10-02 12:57 UTC, SergeyMyronenko commented on src/css/your-order.css
> +    width: 375px;
тут потрібно макс відс

2023-10-02 12:57 UTC, SergeyMyronenko commented on src/css/your-order.css
> +.main-order-container {
тут бажано додати клас .container

2023-10-02 12:57 UTC, SergeyMyronenko commented on src/css/your-order.css
> +    padding-left: 20px;
цей і наступний паддінг не потрібний так як там паддінги повинні бути від контейнера

2023-10-02 12:57 UTC, SergeyMyronenko commented on src/css/your-order.css
> +        width: 768px;
тут теж макс відс повинно бути

2023-10-02 12:57 UTC, SergeyMyronenko commented on src/css/your-order.css
> +    padding-left: 32px;
цей і натупний падінги теж прибрати

2023-10-02 12:57 UTC, SergeyMyronenko commented on src/partials/your-order.html
> +        <img
і тут з зображеннями передивись буль-ласка, в тебе там якесь не завантажується при 1х.В тебе там якісь 2 зображення є orderdesk i orderdasktop можливо неправилно прописані шляхи.

2023-10-03 11:57 UTC, SergeyMyronenko approved these changes

2023-10-03 11:57 UTC, merged

2023-10-04 00:16 UTC, AnnaMakovska commented on src/css/your-order.css
> +    padding-left: 20px;
в контейнера не можуть бути ці падінги, бо контейнер має рівнятись по зображеню дівчини в зеленій сорочці, а в цього зображення немає їх.

2023-10-04 00:23 UTC, AnnaMakovska commented on src/css/your-order.css
> +.main-order-container {
все ламається якщо замінити, твій контейнер не підходить до мого блоку

2023-10-04 01:09 UTC, AnnaMakovska commented on src/partials/your-order.html
> +        <img
дивно, клонувала собі на допрацювання, то зображення і іконка відображаються. правда над зображенням я ще працюю