Our collection
SergeyMyronenko/ukrainian-style pull request #11
Opened 2023-10-02 14:06 UTC by andriishmorgan

2023-10-02 14:48 UTC, SergeyMyronenko requested changes

2023-10-02 14:48 UTC, SergeyMyronenko commented on src/css/our-collection.css
> +.our-collection {
тут падінги не треба вони йдуть від глобальних стилів

2023-10-02 14:48 UTC, SergeyMyronenko commented on src/css/our-collection.css
> +.our-collection-container {
не залишай пустих стилів

2023-10-02 14:48 UTC, SergeyMyronenko commented on src/partials/our-collection.html
> +            srcset="
не розумію в гіт показує шляхи правильно, а коли я відкриваю у вс коді то папка our-collection губиться і зображення не відображаються на локальній сторінці, переглянь будласка як утебе

2023-10-02 14:48 UTC, SergeyMyronenko commented on src/css/our-collection.css
> +  padding: 18px 20px;
тут паддінги не треба, по макету їх там не має

2023-10-02 14:48 UTC, SergeyMyronenko commented on src/css/our-collection.css
> +@media screen and (min-width: 320px) and (max-width: 375px) {
це медіаправило не потрібне

2023-10-02 14:48 UTC, SergeyMyronenko commented on src/css/our-collection.css
> +@media screen and (min-width: 768px) and (max-width: 1280px) {
тут просто повинно бути тільки мін відс

2023-10-02 14:48 UTC, SergeyMyronenko commented on src/css/our-collection.css
> +@media screen and (min-width: 1158px) {
тут мін відс повинно бути 1280

2023-10-02 14:48 UTC, SergeyMyronenko commented on src/css/our-collection.css
> +.our-collection-main-text {
в тебе заголовок не в контейнері тянеться за монітором на мобільній версії

2023-10-02 14:48 UTC, SergeyMyronenko commented on src/css/our-collection.css
> +
в тебе відсутнє медіапрвило для 768 пікселів

2023-10-03 10:45 UTC, andriishmorgan commented on src/css/our-collection.css
> +.our-collection {
Поправив

2023-10-03 10:46 UTC, andriishmorgan commented on src/css/our-collection.css
> +.our-collection-container {
Забрав

2023-10-03 10:46 UTC, andriishmorgan commented on src/partials/our-collection.html
> +            srcset="
Я як відкриваю в ВС коді то в мене все показує, але в мене через 2 крапки, я буду пушити тобі то зроблю тільки через одну, ок?

2023-10-03 10:47 UTC, andriishmorgan commented on src/css/our-collection.css
> +  padding: 18px 20px;
Я їх забрав, але вони там є перепровірь

2023-10-03 10:47 UTC, andriishmorgan commented on src/css/our-collection.css
> +@media screen and (min-width: 320px) and (max-width: 375px) {
Забрав

2023-10-03 10:48 UTC, andriishmorgan commented on src/css/our-collection.css
> +@media screen and (min-width: 768px) and (max-width: 1280px) {
Поправив

2023-10-03 10:48 UTC, andriishmorgan commented on src/css/our-collection.css
> +@media screen and (min-width: 1158px) {
Поправив

2023-10-03 10:49 UTC, andriishmorgan commented on src/css/our-collection.css
> +.our-collection-main-text {
Цього не зрозумів?

2023-10-03 10:49 UTC, andriishmorgan commented on src/css/our-collection.css
> +
є воно , 

/* TABLET */
@media screen and (min-width: 768px) {
  .our-collection-list {
    flex-direction: row;
    flex-wrap: wrap;
    column-gap: 20px;
    row-gap: 20px;
    justify-content: center;
  }
  .our-collection-item {
    width: calc((100% - 40px) / 2);
  }
}

2023-10-03 10:52 UTC, SergeyMyronenko approved these changes

2023-10-03 10:59 UTC, SergeyMyronenko approved these changes

2023-10-03 11:14 UTC, merged